services:
  db:
    image: mysql:8.0
    container_name: shopping-db
    environment:
      MYSQL_ROOT_PASSWORD: shopping_root_pw
      MYSQL_DATABASE: shopping_db
      MYSQL_USER: mayden_shopping
      MYSQL_PASSWORD: mayden_shopping
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "${MYSQL_USER}", "-p${MYSQL_PASSWORD}" ]
      interval: 5s
      timeout: 5s
      retries: 4
      start_period: 10s
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    networks:
      - shopping-network
  app:
    build: .
    container_name: shopping-app
    ports:
      - "9051:9051"
    depends_on:
      db:
        condition: service_healthy
    restart: always
    networks:
      - shopping-network
    environment:
      DB_HOST: shopping-db
volumes:
  db_data:
networks:
  shopping-network:
    driver: bridge